services:
  landing-page:
    image: ghcr.io/${REGISTRY_OWNER:-zryyh}/cora-landing-page:${IMAGE_TAG:-latest}
    container_name: cora-landing-page
    restart: unless-stopped
    networks:
      - npm-proxy

  site-institucional:
    image: ghcr.io/${REGISTRY_OWNER:-zryyh}/cora-site-institucional:${IMAGE_TAG:-latest}
    container_name: cora-site-institucional
    restart: unless-stopped
    networks:
      - npm-proxy

networks:
  npm-proxy:
    external: true
    name: npm-proxy